### ISSUE TITLE
1 mounth different

### ISSUE THREAD

**Issue by squidi** [magicbruno/mb-comingsoon#3]
Hi, thx for this nice countdown, but it shows not the real countdowntime.

Example => today is = 1.8.2014 = 2014, 8, 1, 0, 0

 .mbComingsoon(new Date(2014, 8, 1, 0, 0));

shows => rest to countdown 31 days :(

**Comment by jballanger** [comment]
Hey,

I had the same problem with the following : 
`expiryDate: new Date(2016, 10, 10, 19)`

but with this : 
`expiryDate: new Date(Mon Oct 10 2016 19:00:00)`

it work perfectly
