### ISSUE TITLE
Server time count down

### ISSUE THREAD

**Issue by sumanta-ghosh** [magicbruno/mb-comingsoon#7]
If some one change the browser time then count down timer show wrong data.
Suppose My count down time is 09-Nov-2015  and I manually change my machine date to 15-Nov-2015, then timer stop working because  it's takes client time. 

So it will be best if we pass the current server time when init it.

**Comment by magicbruno** [comment]
It's only a javascript gadget! Then it runs in client browser. However, providein a custom initialisation (or Ajax) could be a good idea for a future version.
